"""
Django settings for sketezo project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


DEBUG = True

ALLOWED_HOSTS = [
    # 'www.thinknshop.in',
    # 'thinknshop.in',
    # 'thinknshopecomm.onrender.com',
    # '127.0.0.1',
   # 'localhost'
   
   "*"
]


from pathlib import Path
from django.core.management.utils import get_random_secret_key  # ✅ ADD THIS LINE

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = get_random_secret_key() 

# Application definition


EMAIL_HOST_USER = "thinknshopofficial@gmail.com"
EMAIL_HOST_PASSWORD = "cbydnvdqihkyuxmz"




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "thinknshopofficial@gmail.com"
EMAIL_HOST_PASSWORD = "cbydnvdqihkyuxmz"  # The App Password (no spaces)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




INSTALLED_APPS = [
 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dev_mode',
    'product',
    'accounts',
    'components',
    'cart',
    'schedule_purchase',
    'address',
    'orders',
    'discount',
    'user_orders',
    'customize',
    'cloudinary',
'cloudinary_storage',
    
  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

ROOT_URLCONF =  'sketezo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sketezo.wsgi.application'



# # For Development Only
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / "db.sqlite3",
#     }
# }

# Production Only (Render PostgreSQL)
import dj_database_url

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default="postgresql://thinknshop_jdjq_user:gPFMloDQ99kMgGozwvqZMrE5VhDsOs4m@dpg-d4t7m9vdiees73atjfug-a.oregon-postgres.render.com/thinknshop_jdjq",
        conn_max_age=600,
        ssl_require=True,
    )
}






# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True


USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Static files (CSS, JavaScript, Images)
# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Enable WhiteNoise storage for compressed and cached static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# For development, optionally still keep additional static dirs
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------
# CLOUDINARY FILE STORAGE (USE DIRECT VALUES HERE)
# ---------------------------------------------------
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dajhsics7',
    'API_KEY': '617272776764369',
    'API_SECRET': 'SfPZ_PrNYvMeEs66SU_uI8KLpSM',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# ---------------------------------------------------


# Extra production flags (recommended)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# # Razorpay Credentials For real payments
RAZORPAY_KEY_ID = "rzp_live_RoklzNDLuPrVaD"
RAZORPAY_KEY_SECRET = "s4AfRsl5rF9H6SKtJJYy3Kyu"

