# Generated by Django 5.2.4 on 2025-11-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='leak_proof',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if the product is leak proof', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='net_weight',
            field=models.CharField(blank=True, help_text='Net weight of the product', max_length=100, null=True),
        ),
    ]
