# Generated by Django 5.2.4 on 2025-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='leak_proof',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='net_weight',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
