# Generated by Django 5.2.4 on 2025-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productvariant_leak_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='size',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='size',
            name='length',
        ),
        migrations.RemoveField(
            model_name='size',
            name='waist',
        ),
        migrations.AddField(
            model_name='size',
            name='volume_ml',
            field=models.PositiveIntegerField(default=950),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('bottle', 'Bottle')], default='bottle', max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(default='950ml', max_length=20),
        ),
    ]
