# Generated by Django 5.1.6 on 2025-08-04 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Custom title for this future purchase', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price willing to pay', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes or special instructions')),
                ('scheduled_date', models.DateTimeField(help_text='When to execute this purchase')),
                ('frequency', models.CharField(choices=[('once', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('action_type', models.CharField(choices=[('reminder', 'Email Reminder Only'), ('auto_purchase', 'Automatic Purchase')], default='reminder', max_length=20)),
                ('reminder_days_before', models.PositiveIntegerField(default=1, help_text='Days before scheduled date to send reminder')),
                ('send_reminder_email', models.BooleanField(default=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('auto_purchase_enabled', models.BooleanField(default=False)),
                ('check_stock_availability', models.BooleanField(default=True, help_text='Check if product is in stock before purchase')),
                ('use_default_address', models.BooleanField(default=True)),
                ('shipping_address', models.TextField(blank=True, help_text='Custom shipping address if not using default')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('next_execution_date', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('max_executions', models.PositiveIntegerField(blank=True, help_text='Maximum times to execute (for recurring)', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_error_message', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly/Total budget limit for this item', max_digits=12, null=True)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_purchases', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_purchases', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, help_text='Specific variant to purchase', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Future Purchase',
                'verbose_name_plural': 'Future Purchases',
                'ordering': ['scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuturePurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('reminder_sent', 'Reminder Sent'), ('execution_attempted', 'Execution Attempted'), ('execution_successful', 'Execution Successful'), ('execution_failed', 'Execution Failed'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=30)),
                ('message', models.TextField(help_text='Detailed message about the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data in JSON format')),
                ('order_id', models.CharField(blank=True, help_text='Order ID if purchase was successful', max_length=100)),
                ('future_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='schedule_purchase.futurepurchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuturePurchaseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], default='email', max_length=20)),
                ('scheduled_for', models.DateTimeField(help_text='When to send this reminder')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, help_text='Email template to use', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('future_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='schedule_purchase.futurepurchase')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='futurepurchase',
            index=models.Index(fields=['user', 'status'], name='schedule_pu_user_id_e1bccb_idx'),
        ),
        migrations.AddIndex(
            model_name='futurepurchase',
            index=models.Index(fields=['scheduled_date', 'is_active'], name='schedule_pu_schedul_ea4146_idx'),
        ),
        migrations.AddIndex(
            model_name='futurepurchase',
            index=models.Index(fields=['next_execution_date'], name='schedule_pu_next_ex_dc6493_idx'),
        ),
        migrations.AddIndex(
            model_name='futurepurchase',
            index=models.Index(fields=['status', 'action_type'], name='schedule_pu_status_e8945e_idx'),
        ),
        migrations.AddIndex(
            model_name='futurepurchaselog',
            index=models.Index(fields=['future_purchase', '-created_at'], name='schedule_pu_future__e098d0_idx'),
        ),
        migrations.AddIndex(
            model_name='futurepurchaselog',
            index=models.Index(fields=['action_type', '-created_at'], name='schedule_pu_action__01d6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='futurepurchasereminder',
            index=models.Index(fields=['scheduled_for', 'status'], name='schedule_pu_schedul_2e0212_idx'),
        ),
        migrations.AddIndex(
            model_name='futurepurchasereminder',
            index=models.Index(fields=['future_purchase', 'reminder_type'], name='schedule_pu_future__973666_idx'),
        ),
    ]
