# Generated by Django 5.1.6 on 2025-08-04 15:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeData',
            fields=[
                ('pincode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('delivery_days', models.IntegerField(default=7, help_text='Estimated delivery days')),
                ('cod_available', models.BooleanField(default=True, help_text='Cash on Delivery available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pincode'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Address label like 'Home', 'Office', etc.", max_length=100)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default address for this user')),
                ('full_name', models.CharField(help_text="Recipient's full name", max_length=100)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line_1', models.CharField(help_text='House/Building number, Street name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, Suite, Floor', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark', max_length=100, null=True)),
                ('pincode', models.CharField(help_text='Postal/ZIP code', max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special delivery instructions', null=True)),
                ('is_apartment', models.BooleanField(default=False, help_text='Is this an apartment/flat?')),
                ('floor_number', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='address_add_user_id_b78d6f_idx'), models.Index(fields=['pincode'], name='address_add_pincode_f4b285_idx'), models.Index(fields=['is_default'], name='address_add_is_defa_ca6edc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user')],
            },
        ),
    ]
