# Generated by Django 5.1.6 on 2025-08-06 06:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('netbanking', 'Net Banking'), ('cod', 'Cash on Delivery'), ('emi', 'EMI')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Processing fee as percentage', max_digits=5)),
                ('processing_fee_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Fixed processing fee', max_digits=10)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount for this payment method', max_digits=10, null=True)),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order amount for this payment method', max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order amount for free shipping', max_digits=10, null=True)),
                ('min_delivery_days', models.PositiveIntegerField(default=1)),
                ('max_delivery_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_express', models.BooleanField(default=False, help_text='Express/priority shipping')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in grams', max_digits=8, null=True)),
                ('restricted_regions', models.TextField(blank=True, help_text='Comma-separated list of restricted states/regions')),
            ],
            options={
                'ordering': ['sort_order', 'base_price'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(help_text='Internal name for the coupon', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description shown to customers')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount for percentage coupons', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount to use coupon', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total usage limit for the coupon', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Usage limit per user')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('first_order_only', models.BooleanField(default=False, help_text='Only for first-time customers')),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Applicable categories', to='product.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Applicable products', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('returned', 'Returned'), ('exchange_requested', 'Exchange Requested')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('payment_gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('payment_gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('carrier_name', models.CharField(blank=True, max_length=100)),
                ('order_notes', models.TextField(blank=True, help_text='Customer notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('is_gift', models.BooleanField(default=False)),
                ('gift_message', models.TextField(blank=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('billing_address', models.ForeignKey(help_text='Billing address snapshot', on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='address.address')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon')),
                ('shipping_address', models.ForeignKey(help_text='Shipping address snapshot', on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.paymentmethod')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.shippingmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(choices=[('cancelled', 'Order Cancelled'), ('returned', 'Product Returned'), ('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Sent'), ('damaged', 'Damaged in Transit'), ('not_as_described', 'Not as Described'), ('change_of_mind', 'Change of Mind'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_gateway_refund_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.order')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=50)),
                ('variant_color', models.CharField(max_length=50)),
                ('variant_size', models.CharField(max_length=20)),
                ('return_status', models.CharField(choices=[('none', 'Not Returned'), ('requested', 'Return Requested'), ('approved', 'Return Approved'), ('shipped', 'Return Shipped'), ('received', 'Return Received'), ('refunded', 'Refunded'), ('exchange_requested', 'Exchange Requested'), ('exchanged', 'Exchanged')], default='none', max_length=20)),
                ('return_reason', models.TextField(blank=True)),
                ('return_quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'product'], name='orders_orde_order_i_52f79a_idx'), models.Index(fields=['variant'], name='orders_orde_variant_164791_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'order_date'], name='orders_orde_status_389324_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
    ]
