# Generated by Django 5.1.6 on 2025-08-19 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('orders', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderrefund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderrefund',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('netbanking', 'Net Banking')], default='cod', max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_n_f3ada5_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_389324_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_payment_bc131d_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_52f79a_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_variant_164791_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='actual_delivery_date',
            new_name='confirmed_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cancelled_at',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='estimated_delivery_date',
            new_name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gift_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_gift',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_gateway_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_gateway_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='requires_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant_color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant_size',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique order identifier', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment gateway reference ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Courier tracking ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_details',
            field=models.CharField(blank=True, help_text='Color and Size info', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='address.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, help_text='Special instructions from customer', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='address.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='orders_orde_order_i_205064_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddField(
            model_name='orderstatusupdate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstatusupdate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='OrderRefund',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.DeleteModel(
            name='OrderTracking',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
