# Generated by Django 5.2.4 on 2025-11-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
