# Generated by Django 5.2.4 on 2025-12-25 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZippypostOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zippypost_order_id', models.CharField(blank=True, help_text='Zipypost internal order ID', max_length=100, null=True, unique=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Courier tracking number', max_length=100, null=True, unique=True)),
                ('awb_number', models.CharField(blank=True, help_text='Air Waybill number', max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, help_text='Assigned courier partner', max_length=255, null=True)),
                ('shipping_status', models.CharField(blank=True, help_text='Current shipping status from Zipypost', max_length=50, null=True)),
                ('label_url', models.URLField(blank=True, help_text='Shipping label PDF URL', null=True)),
                ('is_cod', models.BooleanField(default=False, help_text='Is Cash on Delivery order')),
                ('shipment_created', models.BooleanField(default=False, help_text='Shipment successfully created on Zipypost')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zippypost', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
