# Generated by Django 5.2.4 on 2025-12-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_zippypostorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zippypostorder',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('RTO_INITIATED', 'RTO Initiated'), ('RTO_DELIVERED', 'RTO Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], max_length=50, null=True),
        ),
    ]
