# Generated by Django 5.2.4 on 2025-12-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_zippypostorder_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zippypostorder',
            name='label_url',
            field=models.CharField(blank=True, help_text='Shipping label PDF URL or Path', max_length=5000000, null=True),
        ),
    ]
