# Generated by Django 5.2.4 on 2026-01-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_zippypostorder_label_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NimbuspostOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('awb_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('courier_id', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('RTO_INITIATED', 'RTO Initiated'), ('RTO_DELIVERED', 'RTO Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CREATED', max_length=50)),
                ('label_url', models.TextField(blank=True, null=True)),
                ('manifest_url', models.TextField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nimbuspost', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
